#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <status|sync>"
    exit 1
fi

cd /home/daniel/.task || exit

git fetch

LOCAL=$(git rev-parse HEAD)
REMOTE=$(git rev-parse @{u})
BASE=$(git merge-base HEAD @{u})

check_status() {
    echo 'Checking local changes...'

    if [[ `git status --porcelain` ]]; then
        git status
    else
        echo 'No changes to push'
    fi

    echo 'Checking remote changes'

    if [ "$LOCAL" = "$REMOTE" ]; then
        echo "The repository is up to date."
    elif [ "$LOCAL" = "$BASE" ]; then
        echo "There are remote changes to pull."
    elif [ "$REMOTE" = "$BASE" ]; then
        echo "There are local changes to push."
    else
        echo "The local and remote branches have diverged."
    fi
}

pull_changes() {
    git pull origin master
}

# Function to commit and push changes
sync_changes() {
    if [[ `git status --porcelain` ]]; then
        git add -A

        git commit -m "Automated commit: $(date +"%Y-%m-%d %H:%M:%S")"

        pull_changes

        git push origin master
    else
        echo "No changes to commit"
    fi
}

case "$1" in
    status)
        check_status
        ;;
    sync)
        sync_changes
        ;;
    *)
        echo "Invalid parameter. Usage: $0 <status|sync>"
        exit 1
        ;;
esac

