#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <status|sync>"
    exit 1
fi

check_status() {
    cd /home/daniel/.task || exit

    if [[ `git status --porcelain` ]]; then
        git status
    else
        echo 'No changes'
    fi
}

# Function to commit and push changes
sync_changes() {
    if [[ `git status --porcelain` ]]; then
        git add -A

        git commit -m "Automated commit: $(date +"%Y-%m-%d %H:%M:%S")"

        git push origin master
    else
        echo "No changes to commit"
    fi
}

case "$1" in
    status)
        check_status
        ;;
    sync)
        sync_changes
        ;;
    *)
        echo "Invalid parameter. Usage: $0 <status|sync>"
        exit 1
        ;;
esac

