#!/bin/bash

# Stop on errors
set -e

URL='https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64'
FILE='vscode-latest.deb'

echo 'Downloading VS Code...'
curl -L "$URL" -o "$FILE"

echo 'Installing VS Code...'
sudo dpkg -i "$FILE"

sudo apt-get install -f -y

rm "$FILE"

echo 'VS Code updated successfully. Restart for changes to take effect.'
